spring:
  config:
    import: optional:file:.env[.properties]
  security:
    basic:
      enabled: true
      realm: some-service
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
      roles: [COMMON]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


server:
  servlet:
    context-path: /api/v1/user-service
  port: 8086

logging:
  level:
    org:
      springframework:
        security: DEBUG


topic:
  send-order: email-message-topic